default_config:
  mode: GENERATION
  target_ratio: 2.0

tables:

  - table_name_with_schema: "public.film"
    transformations:
      - columns: ["fulltext"]
        mapping:
          read: "?::text"
          write: "?::tsvector"
        params:
          type: formatted_string_generator
          pattern: "\\+44[0-9]{10}"
      - columns: ["rating"]
        mapping:
          read: "?::text"
          write: "?::mpaa_rating"
        params:
          type: "categorical_generator"
          categories:
            type: STRING
            value_source: PROVIDED
            values:
              "PG-13": 0.223
              "NC-17": 0.21
              "R": 0.195
              "PG": 0.194
              "G": 0.178

  - table_name_with_schema: "public.actor"
    transformations:
      - columns: ["first_name", "last_name"]
        # An example how to preserve the uppercase
        mapping:
          read: "?"
          write: "UPPER(?)"
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}"]

  - table_name_with_schema: "public.country"
    transformations:
      - columns: [ "country" ]
        params:
          type: address_generator
          column_templates: [ "${country}" ]

  - table_name_with_schema: "public.city"
    transformations:
      - columns: [ "city" ]
        params:
          type: address_generator
          column_templates: [ "${city}" ]

  - table_name_with_schema: "public.address"
    transformations:
      - columns: [ "address", "address2" ]
        params:
          type: address_generator
          column_templates:
            - "${street_name}, ${house_number}, ${flat_number}, ${zip_code}"
            - >
              ${country}, ${city}, ${street_name}, ${house_number},
              ${flat_number}, ${zip_code}

  - table_name_with_schema: "public.staff"
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

  - table_name_with_schema: "public.customer"
    transformations:
      - columns: ["first_name", "last_name", "email"]
        params:
          type: person_generator
          column_templates: ["${first_name}", "${last_name}", "${email}"]

table_truncation_mode: "TRUNCATE"
schema_creation_mode: "DO_NOT_CREATE"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
