default_config:
  mode: KEEP
  use_working_directory: true

tables:

  - table_name_with_schema: "public.rental"
    target_ratio: 0.1

  - table_name_with_schema: "public.payment"
    target_ratio: 0.1

  - table_name_with_schema: "public.film"
    transformations:
      - columns: ["fulltext"]
        mapping:
          read: "?::text"
          write: "?::tsvector"
        params:
          type: formatted_string_generator
          pattern: "\\+44[0-9]{10}"
      - columns: ["rating"]
        params:
          type: "categorical_generator"
          categories:
            type: STRING
            value_source: PROVIDED
            values:
              "PG-13": 0.223
              "NC-17": 0.21
              "R": 0.195
              "PG": 0.194
              "G": 0.178


table_truncation_mode: "TRUNCATE"
schema_creation_mode: "CREATE_IF_NOT_EXISTS"
cycle_resolution_strategy: "DELETE_NOT_REQUIRED"
safety_mode: "RELAXED"
